name: build_link
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  latlong2: ^0.8.1
  fl_chart: ^0.55.0
  syncfusion_flutter_datepicker: ^20.2.38
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
  geolocator: ^9.0.0
  flutter_staggered_grid_view: ^0.6.2
  desktop_window: ^0.4.0
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
